name: Project Updater

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  project-updater:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./script
    steps: 
      - name: Check repo
        uses: actions/checkout@v4
        with: 
          persist-credentials: true

      - name: Check dir
        run: pwd
        
      - name: Set permissions
        run: chmod +x project_data_collector.sh
      
      - name: Run script
        run: ./project_data_collector.sh
           
      - name: Commit and push changes
        env: 
          PAT: ${{ secrets.PAT }}  # Using PAT instead of GITHUB_TOKEN
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update from Project Updater" || echo "No changes to commit"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git gh-pages
