name: Project Updater
on: 
  workflow_run:
    workflows: ["pages-build-deployment"]  # Replace with your deployment workflow name
    types:
      - completed
    branches:
      - gh-pages  # or whatever branch your deploy workflow runs on
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # Add explicit permissions


jobs:
  project-updater:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_run' && 
       !contains(github.event.workflow_run.head_commit.message, 'Automated update from Project Updater'))
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./script
    steps: 
      - name: Check repo
        uses: actions/checkout@v4
        with: 
          persist-credentials: true  # Changed to true
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # Use default token

      - name: Check dir
        run: pwd
        
      - name: Set permissions
        run: chmod +x project_data_collector.sh
      
      - name: Run script
        run: ./project_data_collector.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - List files
        run: |
          ls -la
          git status
           
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git status
          git commit -m "Automated update from Project Updater" || echo "No changes to commit"
          git push
